In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

create JSON file

In [1]:
import json
student = {
    "name": "Ayan",
    "age": 21,
    "department": "CSE",
    "semester": 5,
    "subjects": ["AI", "Data Mining", "DBMS"]
}

with open("student.json", "w") as file:
    json.dump(student,file,indent=4)
    print("JSON file created successfully.")

JSON file created successfully.


In [9]:
import pandas as pd
df=pd.read_csv('/kaggle/input/datasets/rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset/fifa_world_cup_2026_player_performance.csv')
print(df.head())

  player_id       player_name  age nationality   team  jersey_number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3   
1    P00070   Ansu Le Normand   19     Spanish  Spain             18   
2    P00066        Gavi Ramos   18     Spanish  Spain             14   
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21   
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7   

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1   
1  Midfielder        178         75          Right  ...               3.5   
2  Midfielder        177         72           Left  ...              15.3   
3     Forward        182         74          Right  ...               1.2   
4    Defender        191         81           Left  ...               6.2   

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9    

In [10]:
import pandas as pd
df=pd.read_csv('/kaggle/input/datasets/rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset/fifa_world_cup_2026_player_performance.csv')
print(df.head())
print(df.describe())
print(df.shape)

  player_id       player_name  age nationality   team  jersey_number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3   
1    P00070   Ansu Le Normand   19     Spanish  Spain             18   
2    P00066        Gavi Ramos   18     Spanish  Spain             14   
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21   
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7   

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1   
1  Midfielder        178         75          Right  ...               3.5   
2  Midfielder        177         72           Left  ...              15.3   
3     Forward        182         74          Right  ...               1.2   
4    Defender        191         81           Left  ...               6.2   

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9    

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

path = "/kaggle/input/datasets/rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset/fifa_world_cup_2026_player_performance.csv"
fifa = pd.read_csv(path)

print("Shape of the dataset:", fifa.shape)
print("\nFirst 5 Rows:")
print(fifa.head())


Shape of the dataset: (54600, 75)

First 5 Rows:
  player_id       player_name  age nationality   team  jersey_number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3   
1    P00070   Ansu Le Normand   19     Spanish  Spain             18   
2    P00066        Gavi Ramos   18     Spanish  Spain             14   
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21   
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7   

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1   
1  Midfielder        178         75          Right  ...               3.5   
2  Midfielder        177         72           Left  ...              15.3   
3     Forward        182         74          Right  ...               1.2   
4    Defender        191         81           Left  ...               6.2   

   pressure_resistance creativity_score consistency_sco

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

dataset_path = "/kaggle/input/datasets/rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset/fifa_world_cup_2026_player_performance.csv"
df = pd.read_csv(dataset_path)

target_col = None
for col in df.columns:
    if "position" in col.lower() or col.lower() == "pos":
        target_col = col
        break

if target_col is None:
    print("Available columns in dataset:")
    print(df.columns.tolist())
    raise KeyError("Could not find a 'Position' column. Please check column names above.")

print(f"Using target column: '{target_col}'")

df = df.dropna(subset=[target_col])

X = df.select_dtypes(include=["int64", "float64"]).fillna(0)
if target_col in X.columns:
    X = X.drop(columns=[target_col])
y = df[target_col]
# 5. Train-Test Split
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
Knn = KNeighborsClassifier(n_neighbors=3)
Knn.fit(x_train, y_train)
y_pred = Knn.predict(x_test)

print("\nPredicted Species/Position:")
print(y_pred)
print("\nActual Species/Position:")
print(y_test.values)
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy * 100, "%")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Using target column: 'position'

Predicted Species/Position:
['Defender' 'Midfielder' 'Midfielder' ... 'Defender' 'Forward'
 'Midfielder']

Actual Species/Position:
['Defender' 'Midfielder' 'Midfielder' ... 'Defender' 'Forward'
 'Midfielder']

Accuracy: 99.97252747252747 %

Confusion Matrix:
[[3827    0    1    0]
 [   0 2478    0    1]
 [   0    0 1266    0]
 [   1    0    0 3346]]

Classification Report:
              precision    recall  f1-score   support

    Defender       1.00      1.00      1.00      3828
     Forward       1.00      1.00      1.00      2479
  Goalkeeper       1.00      1.00      1.00      1266
  Midfielder       1.00      1.00      1.00      3347

    accuracy                           1.00     10920
   macro avg       1.00      1.00      1.00     10920
weighted avg       1.00      1.00      1.00     10920

